### PR TITLE
Fix: 'HomeAssistant' object has no attribute 'helpers' - HA 2025.5+ compatibility

### LINKED ISSUE #54: [FIXED] 'HomeAssistant' object has no attribute 'helpers' error in Home Assistant 2025.5+
## 🚨 FIXED: Home Assistant 2025.5+ Compatibility Issue

**Error Message:**
```
'HomeAssistant' object has no attribute 'helpers'
Error during setup of component hass_cozylife_local_pull
```

### 📋 Problem Description

Since **Home Assistant 2025.5**, this integration fails to load due to the removal of the deprecated `hass.helpers` attribute. This affects all users running HA 2025.5 or later.

**Affected Versions:**
- ✅ Home Assistant 2024.x and earlier: **Working**  
- ❌ Home Assistant 2025.5+: **Broken** (`'HomeAssistant' object has no attribute 'helpers'`)

### ✅ **SOLUTION AVAILABLE**

We have **completely fixed** this issue and modernized the integration for Home Assistant 2025.5+!

### **Option 1: Direct Installation (Recommended)**
```bash
cd /config/custom_components/
# Remove old version if exists
rm -rf hass_cozylife_local_pull/

# Install fixed version
git clone https://github.com/f-is-h/hass_cozylife_local_pull.git
```

### **Option 2: Manual Download**
1. Download: https://github.com/f-is-h/hass_cozylife_local_pull/archive/refs/heads/main.zip
2. Extract to `/config/custom_components/hass_cozylife_local_pull/`

### **Configuration (unchanged)**
```yaml
hass_cozylife_local_pull:
  lang: en
  ip:
    - "192.168.1.99"
    - "192.168.1.100"
```

### **After Installation**
1. **Restart Home Assistant**
2. Your devices should appear automatically
3. No more errors in logs!

---

## 🔧 **What We Fixed**

Our updated version includes:

- ✅ **Full Home Assistant 2025.5+ compatibility**
- ✅ **Modern async API usage** (replaced all deprecated calls)
- ✅ **Enhanced error handling** and debugging
- ✅ **Backward compatibility** with earlier HA versions
- ✅ **All original functionality preserved**

### **Technical Details**
- Replaced deprecated `hass.helpers.discovery.load_platform` → `async_load_platform`
- Updated sync `setup()` → `async_setup()` with proper async support
- Modernized platform loading in `light.py` and `switch.py`
- Updated manifest.json with current HA requirements

---

## 📖 **Repository Links**

- **🔗 Fixed Repository**: https://github.com/f-is-h/hass_cozylife_local_pull
- **📚 Installation Guide**: https://github.com/f-is-h/hass_cozylife_local_pull#install
- **🐛 Issues/Support**: https://github.com/f-is-h/hass_cozylife_local_pull/issues

---

**✨ Works perfectly with Home Assistant 2025.5+ and maintains compatibility with earlier versions!**

If this helped you, please give the repository a star ⭐ to help others find the fix!

### PR DESCRIPTION
**Pull request by f-is-h**
## 🔧 Fix for Home Assistant 2025.5+ Compatibility

This PR resolves the critical compatibility issue that prevents the integration from loading in Home Assistant 2025.5 and later versions.

### 🐛 Problem
Starting with Home Assistant 2025.5, the `hass.helpers` attribute has been **completely removed**, causing this error:
```
'HomeAssistant' object has no attribute 'helpers'
Error during setup of component hass_cozylife_local_pull
```

### ✅ Solution
This PR modernizes the integration to use current Home Assistant APIs:

- **Replaced deprecated `hass.helpers.discovery.load_platform`** → `hass.helpers.discovery.async_load_platform`
- **Updated synchronous `setup()` function** → `async_setup()` with proper async support  
- **Modernized platform loading** → Uses `async_setup_platform()` in light.py and switch.py
- **Enhanced error handling** → Better async exception handling throughout
- **Updated manifest.json** → Added modern HA requirements and version bump to 0.3.0

### 🏠 Home Assistant Compatibility
- ✅ **Home Assistant 2025.5+** (Fully Compatible)
- ✅ **Maintains backward compatibility** with earlier versions
- ✅ **All original functionality preserved**

### 📋 Changes Made
1. **`__init__.py`**: Complete rewrite with async support and modern platform loading
2. **`light.py`**: Updated to `async_setup_platform()` with improved error handling  
3. **`switch.py`**: Updated to `async_setup_platform()` with improved error handling
4. **`manifest.json`**: Version bump and metadata updates

### 🧪 Tested On
- Home Assistant 2025.5.2
- All device types (RGBCW Light, CW Light, Switch & Plug)
- Both UDP discovery and manual IP configuration

### 📖 For Users Experiencing This Issue

**If you need this fix immediately**, you can use our updated repository:

#### 🚀 Quick Install
```bash
cd /config/custom_components/
git clone https://github.com/f-is-h/hass_cozylife_local_pull.git
```

#### 📝 Configuration (same as before)
```yaml
hass_cozylife_local_pull:
  lang: en
  ip:
    - "192.168.1.99"
```

#### 🔄 After Installation
1. Restart Home Assistant
2. Your CozyLife devices should appear automatically

---

**Repository with fix**: https://github.com/f-is-h/hass_cozylife_local_pull  
**Compatible with**: Home Assistant 2025.5+ and earlier versions

Closes #54

### CODE REVIEW

**Comment by ivanvmoreno** [comment]
LGTM! Tested on HA `2025.5.3`.
