### ISSUE TITLE
[FIXED] 'HomeAssistant' object has no attribute 'helpers' error in Home Assistant 2025.5+

### ISSUE THREAD

**Issue by f-is-h** [cozylife/hass_cozylife_local_pull#54]
## 🚨 FIXED: Home Assistant 2025.5+ Compatibility Issue

**Error Message:**
```
'HomeAssistant' object has no attribute 'helpers'
Error during setup of component hass_cozylife_local_pull
```

### 📋 Problem Description

Since **Home Assistant 2025.5**, this integration fails to load due to the removal of the deprecated `hass.helpers` attribute. This affects all users running HA 2025.5 or later.

**Affected Versions:**
- ✅ Home Assistant 2024.x and earlier: **Working**  
- ❌ Home Assistant 2025.5+: **Broken** (`'HomeAssistant' object has no attribute 'helpers'`)

### ✅ **SOLUTION AVAILABLE**

We have **completely fixed** this issue and modernized the integration for Home Assistant 2025.5+!

### **Option 1: Direct Installation (Recommended)**
```bash
cd /config/custom_components/
# Remove old version if exists
rm -rf hass_cozylife_local_pull/

# Install fixed version
git clone https://github.com/f-is-h/hass_cozylife_local_pull.git
```

### **Option 2: Manual Download**
1. Download: https://github.com/f-is-h/hass_cozylife_local_pull/archive/refs/heads/main.zip
2. Extract to `/config/custom_components/hass_cozylife_local_pull/`

### **Configuration (unchanged)**
```yaml
hass_cozylife_local_pull:
  lang: en
  ip:
    - "192.168.1.99"
    - "192.168.1.100"
```

### **After Installation**
1. **Restart Home Assistant**
2. Your devices should appear automatically
3. No more errors in logs!

---

## 🔧 **What We Fixed**

Our updated version includes:

- ✅ **Full Home Assistant 2025.5+ compatibility**
- ✅ **Modern async API usage** (replaced all deprecated calls)
- ✅ **Enhanced error handling** and debugging
- ✅ **Backward compatibility** with earlier HA versions
- ✅ **All original functionality preserved**

### **Technical Details**
- Replaced deprecated `hass.helpers.discovery.load_platform` → `async_load_platform`
- Updated sync `setup()` → `async_setup()` with proper async support
- Modernized platform loading in `light.py` and `switch.py`
- Updated manifest.json with current HA requirements

---

## 📖 **Repository Links**

- **🔗 Fixed Repository**: https://github.com/f-is-h/hass_cozylife_local_pull
- **📚 Installation Guide**: https://github.com/f-is-h/hass_cozylife_local_pull#install
- **🐛 Issues/Support**: https://github.com/f-is-h/hass_cozylife_local_pull/issues

---

**✨ Works perfectly with Home Assistant 2025.5+ and maintains compatibility with earlier versions!**

If this helped you, please give the repository a star ⭐ to help others find the fix!

**Comment by wqianglxf** [comment]
Error during setup of component hass_cozylife_local_pull: 'HomeAssistant' object has no attribute 'helpers'
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/homeassistant/setup.py", line 426, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/hass_cozylife_local_pull/__init__.py", line 52, in setup
    hass.helpers.discovery.load_platform('light', DOMAIN, {}, config)
    ^^^^^^^^^^^^
AttributeError: 'HomeAssistant' object has no attribute 'helpers'

**Comment by f-is-h** [comment]
@wqianglxf 
So you need to use my repository, and follow the README to fix this error.

**Comment by wqianglxf** [comment]
Thank you, I will follow your repository
Successfully followed the readme to fix this error
Wishing you a happy life
